In [33]:
import os
import json
import pandas as pd
from datetime import datetime

def load_json_data(filepath):
    with open(filepath, 'r') as file:
        return json.load(file)

In [34]:
# Pfad zum aktuellen Verzeichnis
current_dir = os.getcwd()

# Pfad zum übergeordneten Verzeichnis
parent_dir = os.path.abspath(os.path.join(current_dir, ".."))
print(parent_dir)

/Users/asuka/Desktop/Digital-health_technisch/DailyStress

In [35]:
filepath = parent_dir + '/data/Liza/stress_data.json'
stress_data = load_json_data(filepath)

print(type(stress_data))
print(stress_data)

<class 'list'>

In [36]:
def parse_stress_data(stress_data):
    stress_summary = []
    for record in stress_data:
        start_time_str = record.get('startTimestampLocal')
        end_time_str = record.get('endTimestampLocal')
        
        # Überprüfe, ob die Werte für start_time_str und end_time_str vorhanden sind
        if start_time_str and end_time_str:
            start_time = datetime.strptime(start_time_str, "%Y-%m-%dT%H:%M:%S.%f")
            end_time = datetime.strptime(end_time_str, "%Y-%m-%dT%H:%M:%S.%f")
            duration_hours = (end_time - start_time).total_seconds() / 3600
            summary = {
                'date': record['calendarDate'],
                'max_stress_level': record['maxStressLevel'],
                'average_stress_level': record['avgStressLevel'],
                'stress_duration': duration_hours
            }
            stress_summary.append(summary)
    return stress_summary

# Beispiel für das Laden und Parsen der Daten
stress_summary = parse_stress_data(stress_data)
print(stress_summary)
df_stress = pd.DataFrame(stress_summary)

[{'date': '2023-12-07', 'max_stress_level': 97, 'average_stress_level': 43, 'stress_duration': 24.0}, {'date': '2023-12-08', 'max_stress_level': 92, 'average_stress_level': 38, 'stress_duration': 24.0}, {'date': '2023-12-09', 'max_stress_level': 94, 'average_stress_level': 47, 'stress_duration': 24.0}, {'date': '2023-12-10', 'max_stress_level': 82, 'average_stress_level': 34, 'stress_duration': 24.0}, {'date': '2023-12-11', 'max_stress_level': 94, 'average_stress_level': 33, 'stress_duration': 24.0}, {'date': '2023-12-12', 'max_stress_level': 98, 'average_stress_level': 39, 'stress_duration': 24.0}, {'date': '2023-12-13', 'max_stress_level': 82, 'average_stress_level': 47, 'stress_duration': 24.0}, {'date': '2023-12-14', 'max_stress_level': 94, 'average_stress_level': 33, 'stress_duration': 24.0}, {'date': '2023-12-15', 'max_stress_level': 91, 'average_stress_level': 27, 'stress_duration': 24.0}, {'date': '2023-12-16', 'max_stress_level': 93, 'average_stress_level': 22, 'stress_duration': 24.0}, {'date': '2023-12-17', 'max_stress_level': 91, 'average_stress_level': 26, 'stress_duration': 24.0}, {'date': '2023-12-18', 'max_stress_level': 93, 'average_stress_level': 20, 'stress_duration': 24.0}, {'date': '2023-12-19', 'max_stress_level': 95, 'average_stress_level': 23, 'stress_duration': 24.0}, {'date': '2023-12-20', 'max_stress_level': 99, 'average_stress_level': 32, 'stress_duration': 24.0}, {'date': '2023-12-21', 'max_stress_level': 93, 'average_stress_level': 35, 'stress_duration': 24.0}, {'date': '2023-12-22', 'max_stress_level': 98, 'average_stress_level': 33, 'stress_duration': 24.0}, {'date': '2023-12-23', 'max_stress_level': 94, 'average_stress_level': 68, 'stress_duration': 24.0}, {'date': '2023-12-24', 'max_stress_level': 97, 'average_stress_level': 29, 'stress_duration': 24.0}, {'date': '2023-12-25', 'max_stress_level': None, 'average_stress_level': -1, 'stress_duration': 24.0}, {'date': '2023-12-26', 'max_stress_level': None, 'average_stress_level': -1, 'stress_duration': 16.366666666666667}]

In [37]:
df_stress.dropna(axis=0)

          date  max_stress_level  average_stress_level  stress_duration
0   2023-12-07              97.0                    43             24.0
1   2023-12-08              92.0                    38             24.0
2   2023-12-09              94.0                    47             24.0
3   2023-12-10              82.0                    34             24.0
4   2023-12-11              94.0                    33             24.0
5   2023-12-12              98.0                    39             24.0
6   2023-12-13              82.0                    47             24.0
7   2023-12-14              94.0                    33             24.0
8   2023-12-15              91.0                    27             24.0
9   2023-12-16              93.0                    22             24.0
10  2023-12-17              91.0                    26             24.0
11  2023-12-18              93.0                    20             24.0
12  2023-12-19              95.0                    23             24.0
13  2023-12-20              99.0                    32             24.0
14  2023-12-21              93.0                    35             24.0
15  2023-12-22              98.0                    33             24.0
16  2023-12-23              94.0                    68             24.0
17  2023-12-24              97.0                    29             24.0

In [38]:
filepath = parent_dir + '/data/Liza/sleep_data.json'
sleep_data = load_json_data(filepath)

print(type(sleep_data))

<class 'list'>

In [39]:
def parse_sleep_data(sleep_data):
    sleep_summary = []
    for item in sleep_data:
        record = item['dailySleepDTO']
        summary = {
            'date': record['calendarDate'],
            'total_sleep_time': record['sleepTimeSeconds'] / 3600 if record['sleepTimeSeconds'] is not None else None,  # In Stunden umrechnen
            'sleep_quality': record['sleepQualityTypePK']
        }
        sleep_summary.append(summary)
    return sleep_summary


sleep_summary = parse_sleep_data(sleep_data)
print(sleep_summary)
df_sleep = pd.DataFrame(sleep_summary)

[{'date': '2023-12-07', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2023-12-08', 'total_sleep_time': 10.216666666666667, 'sleep_quality': None}, {'date': '2023-12-09', 'total_sleep_time': 8.316666666666666, 'sleep_quality': None}, {'date': '2023-12-10', 'total_sleep_time': 6.966666666666667, 'sleep_quality': None}, {'date': '2023-12-11', 'total_sleep_time': 5.95, 'sleep_quality': None}, {'date': '2023-12-12', 'total_sleep_time': 8.633333333333333, 'sleep_quality': None}, {'date': '2023-12-13', 'total_sleep_time': 7.866666666666666, 'sleep_quality': None}, {'date': '2023-12-14', 'total_sleep_time': 6.633333333333334, 'sleep_quality': None}, {'date': '2023-12-15', 'total_sleep_time': 8.916666666666666, 'sleep_quality': None}, {'date': '2023-12-16', 'total_sleep_time': 10.566666666666666, 'sleep_quality': None}, {'date': '2023-12-17', 'total_sleep_time': 7.016666666666667, 'sleep_quality': None}, {'date': '2023-12-18', 'total_sleep_time': 8.382222222222222, 'sleep_quality': None}, {'date': '2023-12-19', 'total_sleep_time': 6.4, 'sleep_quality': None}, {'date': '2023-12-20', 'total_sleep_time': 8.583333333333334, 'sleep_quality': None}, {'date': '2023-12-21', 'total_sleep_time': 6.983333333333333, 'sleep_quality': None}, {'date': '2023-12-22', 'total_sleep_time': 6.666666666666667, 'sleep_quality': None}, {'date': '2023-12-23', 'total_sleep_time': 8.383333333333333, 'sleep_quality': None}, {'date': '2023-12-24', 'total_sleep_time': 9.116666666666667, 'sleep_quality': None}, {'date': '2023-12-25', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2023-12-26', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2023-12-27', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2023-12-28', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2023-12-29', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2023-12-30', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2023-12-31', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-01', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-02', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-03', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-04', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-05', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-06', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-07', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-08', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-09', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-10', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-11', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-12', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-13', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-14', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-15', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-16', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-17', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-18', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-19', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-20', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-21', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-22', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-23', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-24', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-25', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-26', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-27', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-28', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-29', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-30', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-01-31', 'total_sleep_time': None, 'sleep_quality': None}, {'date': '2024-02-01', 'total_sleep_time': None, 'sleep_quality': None}]

In [40]:
df_sleep.drop(0).drop(df_sleep.index[18:])

          date  total_sleep_time sleep_quality
1   2023-12-08         10.216667          None
2   2023-12-09          8.316667          None
3   2023-12-10          6.966667          None
4   2023-12-11          5.950000          None
5   2023-12-12          8.633333          None
6   2023-12-13          7.866667          None
7   2023-12-14          6.633333          None
8   2023-12-15          8.916667          None
9   2023-12-16         10.566667          None
10  2023-12-17          7.016667          None
11  2023-12-18          8.382222          None
12  2023-12-19          6.400000          None
13  2023-12-20          8.583333          None
14  2023-12-21          6.983333          None
15  2023-12-22          6.666667          None
16  2023-12-23          8.383333          None
17  2023-12-24          9.116667          None

In [41]:
filepath = parent_dir + '/data/Liza/heart_rates.json'
heart_rate_data = load_json_data(filepath)

print(type(heart_rate_data))

<class 'list'>

In [42]:
def parse_heart_rate_data(heart_rate_data):
    heart_rate_summary = []
    for item in heart_rate_data:
        record = item  # Da jedes Element bereits ein Dictionary ist, brauchen wir keine spezifische Unterteilung
        summary = {
            'date': record['calendarDate'],
            'max_heart_rate': record['maxHeartRate'],
            'min_heart_rate': record['minHeartRate'],
            'resting_heart_rate': record['restingHeartRate'],
        }
        heart_rate_summary.append(summary)
    return heart_rate_summary

heart_rate_summary = parse_heart_rate_data(heart_rate_data)
print(heart_rate_summary)
df_heart_rate = pd.DataFrame(heart_rate_summary)

[{'date': '2023-12-07', 'max_heart_rate': 134, 'min_heart_rate': 68, 'resting_heart_rate': 72}, {'date': '2023-12-08', 'max_heart_rate': 124, 'min_heart_rate': 65, 'resting_heart_rate': 69}, {'date': '2023-12-09', 'max_heart_rate': 130, 'min_heart_rate': 73, 'resting_heart_rate': 75}, {'date': '2023-12-10', 'max_heart_rate': 110, 'min_heart_rate': 70, 'resting_heart_rate': 73}, {'date': '2023-12-11', 'max_heart_rate': 134, 'min_heart_rate': 67, 'resting_heart_rate': 67}, {'date': '2023-12-12', 'max_heart_rate': 128, 'min_heart_rate': 68, 'resting_heart_rate': 69}, {'date': '2023-12-13', 'max_heart_rate': 102, 'min_heart_rate': 68, 'resting_heart_rate': 66}, {'date': '2023-12-14', 'max_heart_rate': 123, 'min_heart_rate': 65, 'resting_heart_rate': 69}, {'date': '2023-12-15', 'max_heart_rate': 112, 'min_heart_rate': 64, 'resting_heart_rate': 70}, {'date': '2023-12-16', 'max_heart_rate': 127, 'min_heart_rate': 63, 'resting_heart_rate': 65}, {'date': '2023-12-17', 'max_heart_rate': 109, 'min_heart_rate': 64, 'resting_heart_rate': 65}, {'date': '2023-12-18', 'max_heart_rate': 126, 'min_heart_rate': 60, 'resting_heart_rate': 62}, {'date': '2023-12-19', 'max_heart_rate': 112, 'min_heart_rate': 62, 'resting_heart_rate': 63}, {'date': '2023-12-20', 'max_heart_rate': 127, 'min_heart_rate': 40, 'resting_heart_rate': 55}, {'date': '2023-12-21', 'max_heart_rate': 112, 'min_heart_rate': 63, 'resting_heart_rate': 72}, {'date': '2023-12-22', 'max_heart_rate': 142, 'min_heart_rate': 64, 'resting_heart_rate': 67}, {'date': '2023-12-23', 'max_heart_rate': 120, 'min_heart_rate': 81, 'resting_heart_rate': 64}, {'date': '2023-12-24', 'max_heart_rate': 119, 'min_heart_rate': 66, 'resting_heart_rate': 68}, {'date': '2023-12-25', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2023-12-26', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2023-12-27', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2023-12-28', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2023-12-29', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2023-12-30', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2023-12-31', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-01', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-02', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-03', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-04', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-05', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-06', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-07', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-08', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-09', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-10', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-11', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-12', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-13', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-14', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-15', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-16', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-17', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-18', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-19', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-20', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-21', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-22', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-23', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-24', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-25', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-26', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-27', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-28', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-29', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-30', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-01-31', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}, {'date': '2024-02-01', 'max_heart_rate': None, 'min_heart_rate': None, 'resting_heart_rate': None}]

In [43]:
df_heart_rate.dropna(axis=0)

          date  max_heart_rate  min_heart_rate  resting_heart_rate
0   2023-12-07           134.0            68.0                72.0
1   2023-12-08           124.0            65.0                69.0
2   2023-12-09           130.0            73.0                75.0
3   2023-12-10           110.0            70.0                73.0
4   2023-12-11           134.0            67.0                67.0
5   2023-12-12           128.0            68.0                69.0
6   2023-12-13           102.0            68.0                66.0
7   2023-12-14           123.0            65.0                69.0
8   2023-12-15           112.0            64.0                70.0
9   2023-12-16           127.0            63.0                65.0
10  2023-12-17           109.0            64.0                65.0
11  2023-12-18           126.0            60.0                62.0
12  2023-12-19           112.0            62.0                63.0
13  2023-12-20           127.0            40.0                55.0
14  2023-12-21           112.0            63.0                72.0
15  2023-12-22           142.0            64.0                67.0
16  2023-12-23           120.0            81.0                64.0
17  2023-12-24           119.0            66.0                68.0

In [44]:
filepath = parent_dir + '/data/Liza/body_battery.json'
body_battery_data = load_json_data(filepath)

print(type(body_battery_data))

<class 'list'>

In [45]:
def parse_body_battery_data(body_battery_data):
    body_battery_summary = []
    for item in body_battery_data:
        for record in item:
            summary = {
                'date': record['date'],
                'charged': record['charged'],
                'drained': record['drained'],
                'start_time_gmt': record['startTimestampGMT'],
                'end_time_gmt': record['endTimestampGMT'],
                'start_time_local': record['startTimestampLocal'],
                'end_time_local': record['endTimestampLocal'],
            }
            body_battery_summary.append(summary)
    return body_battery_summary

body_battery_summary = parse_body_battery_data(body_battery_data)
print(body_battery_summary)
df_body_battery = pd.DataFrame(body_battery_summary)

[{'date': '2023-12-07', 'charged': 4, 'drained': 49, 'start_time_gmt': '2023-12-06T23:00:00.0', 'end_time_gmt': '2023-12-07T23:00:00.0', 'start_time_local': '2023-12-07T00:00:00.0', 'end_time_local': '2023-12-08T00:00:00.0'}, {'date': '2023-12-08', 'charged': 54, 'drained': 54, 'start_time_gmt': '2023-12-07T23:00:00.0', 'end_time_gmt': '2023-12-08T23:00:00.0', 'start_time_local': '2023-12-08T00:00:00.0', 'end_time_local': '2023-12-09T00:00:00.0'}, {'date': '2023-12-09', 'charged': 26, 'drained': 27, 'start_time_gmt': '2023-12-08T23:00:00.0', 'end_time_gmt': '2023-12-09T23:00:00.0', 'start_time_local': '2023-12-09T00:00:00.0', 'end_time_local': '2023-12-10T00:00:00.0'}, {'date': '2023-12-10', 'charged': 36, 'drained': 8, 'start_time_gmt': '2023-12-09T23:00:00.0', 'end_time_gmt': '2023-12-10T23:00:00.0', 'start_time_local': '2023-12-10T00:00:00.0', 'end_time_local': '2023-12-11T00:00:00.0'}, {'date': '2023-12-11', 'charged': 37, 'drained': 40, 'start_time_gmt': '2023-12-10T23:00:00.0', 'end_time_gmt': '2023-12-11T23:00:00.0', 'start_time_local': '2023-12-11T00:00:00.0', 'end_time_local': '2023-12-12T00:00:00.0'}, {'date': '2023-12-12', 'charged': 68, 'drained': 71, 'start_time_gmt': '2023-12-11T23:00:00.0', 'end_time_gmt': '2023-12-12T23:00:00.0', 'start_time_local': '2023-12-12T00:00:00.0', 'end_time_local': '2023-12-13T00:00:00.0'}, {'date': '2023-12-13', 'charged': 0, 'drained': 6, 'start_time_gmt': '2023-12-12T23:00:00.0', 'end_time_gmt': '2023-12-13T23:00:00.0', 'start_time_local': '2023-12-13T00:00:00.0', 'end_time_local': '2023-12-14T00:00:00.0'}, {'date': '2023-12-14', 'charged': 42, 'drained': 47, 'start_time_gmt': '2023-12-13T23:00:00.0', 'end_time_gmt': '2023-12-14T23:00:00.0', 'start_time_local': '2023-12-14T00:00:00.0', 'end_time_local': '2023-12-15T00:00:00.0'}, {'date': '2023-12-15', 'charged': 61, 'drained': 55, 'start_time_gmt': '2023-12-14T23:00:00.0', 'end_time_gmt': '2023-12-15T23:00:00.0', 'start_time_local': '2023-12-15T00:00:00.0', 'end_time_local': '2023-12-16T00:00:00.0'}, {'date': '2023-12-16', 'charged': 75, 'drained': 50, 'start_time_gmt': '2023-12-15T23:00:00.0', 'end_time_gmt': '2023-12-16T23:00:00.0', 'start_time_local': '2023-12-16T00:00:00.0', 'end_time_local': '2023-12-17T00:00:00.0'}, {'date': '2023-12-17', 'charged': 50, 'drained': 37, 'start_time_gmt': '2023-12-16T23:00:00.0', 'end_time_gmt': '2023-12-17T23:00:00.0', 'start_time_local': '2023-12-17T00:00:00.0', 'end_time_local': '2023-12-18T00:00:00.0'}, {'date': '2023-12-18', 'charged': 78, 'drained': 63, 'start_time_gmt': '2023-12-17T23:00:00.0', 'end_time_gmt': '2023-12-18T23:00:00.0', 'start_time_local': '2023-12-18T00:00:00.0', 'end_time_local': '2023-12-19T00:00:00.0'}, {'date': '2023-12-19', 'charged': 51, 'drained': 38, 'start_time_gmt': '2023-12-18T23:00:00.0', 'end_time_gmt': '2023-12-19T23:00:00.0', 'start_time_local': '2023-12-19T00:00:00.0', 'end_time_local': '2023-12-20T00:00:00.0'}, {'date': '2023-12-20', 'charged': 71, 'drained': 66, 'start_time_gmt': '2023-12-19T23:00:00.0', 'end_time_gmt': '2023-12-20T23:00:00.0', 'start_time_local': '2023-12-20T00:00:00.0', 'end_time_local': '2023-12-21T00:00:00.0'}, {'date': '2023-12-21', 'charged': 35, 'drained': 40, 'start_time_gmt': '2023-12-20T23:00:00.0', 'end_time_gmt': '2023-12-21T23:00:00.0', 'start_time_local': '2023-12-21T00:00:00.0', 'end_time_local': '2023-12-22T00:00:00.0'}, {'date': '2023-12-22', 'charged': 76, 'drained': 65, 'start_time_gmt': '2023-12-21T23:00:00.0', 'end_time_gmt': '2023-12-22T23:00:00.0', 'start_time_local': '2023-12-22T00:00:00.0', 'end_time_local': '2023-12-23T00:00:00.0'}, {'date': '2023-12-23', 'charged': 0, 'drained': 22, 'start_time_gmt': '2023-12-22T23:00:00.0', 'end_time_gmt': '2023-12-23T23:00:00.0', 'start_time_local': '2023-12-23T00:00:00.0', 'end_time_local': '2023-12-24T00:00:00.0'}, {'date': '2023-12-24', 'charged': 53, 'drained': 26, 'start_time_gmt': '2023-12-23T23:00:00.0', 'end_time_gmt': '2023-12-24T23:00:00.0', 'start_time_local': '2023-12-24T00:00:00.0', 'end_time_local': '2023-12-25T00:00:00.0'}, {'date': '2023-12-25', 'charged': None, 'drained': None, 'start_time_gmt': '2023-12-24T23:00:00.0', 'end_time_gmt': '2023-12-25T23:00:00.0', 'start_time_local': '2023-12-25T00:00:00.0', 'end_time_local': '2023-12-26T00:00:00.0'}, {'date': '2023-12-26', 'charged': None, 'drained': None, 'start_time_gmt': '2023-12-25T23:00:00.0', 'end_time_gmt': '2023-12-26T15:22:00.0', 'start_time_local': '2023-12-26T00:00:00.0', 'end_time_local': '2023-12-26T16:22:00.0'}, {'date': '2023-12-27', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2023-12-28', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2023-12-29', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2023-12-30', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2023-12-31', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-01', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-02', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-03', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-04', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-05', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-06', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-07', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-08', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-09', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-10', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-11', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-12', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-13', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-14', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-15', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-16', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-17', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-18', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-19', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-20', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-21', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-22', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-23', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-24', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-25', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-26', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-27', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-28', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-29', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-30', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-01-31', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}, {'date': '2024-02-01', 'charged': None, 'drained': None, 'start_time_gmt': None, 'end_time_gmt': None, 'start_time_local': None, 'end_time_local': None}]

In [46]:
df_body_battery.dropna(axis=0)

,date,charged,drained,start_time_gmt,end_time_gmt,start_time_local,end_time_local
0,2023-12-07,4.0,49.0,2023-12-06T23:00:00.0,2023-12-07T23:00:00.0,2023-12-07T00:00:00.0,2023-12-08T00:00:00.0
1,2023-12-08,54.0,54.0,2023-12-07T23:00:00.0,2023-12-08T23:00:00.0,2023-12-08T00:00:00.0,2023-12-09T00:00:00.0
2,2023-12-09,26.0,27.0,2023-12-08T23:00:00.0,2023-12-09T23:00:00.0,2023-12-09T00:00:00.0,2023-12-10T00:00:00.0
3,2023-12-10,36.0,8.0,2023-12-09T23:00:00.0,2023-12-10T23:00:00.0,2023-12-10T00:00:00.0,2023-12-11T00:00:00.0
4,2023-12-11,37.0,40.0,2023-12-10T23:00:00.0,2023-12-11T23:00:00.0,2023-12-11T00:00:00.0,2023-12-12T00:00:00.0
5,2023-12-12,68.0,71.0,2023-12-11T23:00:00.0,2023-12-12T23:00:00.0,2023-12-12T00:00:00.0,2023-12-13T00:00:00.0
6,2023-12-13,0.0,6.0,2023-12-12T23:00:00.0,2023-12-13T23:00:00.0,2023-12-13T00:00:00.0,2023-12-14T00:00:00.0
7,2023-12-14,42.0,47.0,2023-12-13T23:00:00.0,2023-12-14T23:00:00.0,2023-12-14T00:00:00.0,2023-12-15T00:00:00.0
8,2023-12-15,61.0,55.0,2023-12-14T23:00:00.0,2023-12-15T23:00:00.0,2023-12-15T00:00:00.0,2023-12-16T00:00:00.0
9,2023-12-16,75.0,50.0,2023-12-15T23:00:00.0,2023-12-16T23:00:00.0,2023-12-16T00:00:00.0,2023-12-17T00:00:00.0
10,2023-12-17,50.0,37.0,2023-12-16T23:00:00.0,2023-12-17T23:00:00.0,2023-12-17T00:00:00.0,2023-12-18T00:00:00.0
11,2023-12-18,78.0,63.0,2023-12-17T23:00:00.0,2023-12-18T23:00:00.0,2023-12-18T00:00:00.0,2023-12-19T00:00:00.0
12,2023-12-19,51.0,38.0,2023-12-18T23:00:00.0,2023-12-19T23:00:00.0,2023-12-19T00:00:00.0,2023-12-20T00:00:00.0
13,2023-12-20,71.0,66.0,2023-12-19T23:00:00.0,2023-12-20T23:00:00.0,2023-12-20T00:00:00.0,2023-12-21T00:00:00.0
14,2023-12-21,35.0,40.0,2023-12-20T23:00:00.0,2023-12-21T23:00:00.0,2023-12-21T00:00:00.0,2023-12-22T00:00:00.0
15,2023-12-22,76.0,65.0,2023-12-21T23:00:00.0,2023-12-22T23:00:00.0,2023-12-22T00:00:00.0,2023-12-23T00:00:00.0
16,2023-12-23,0.0,22.0,2023-12-22T23:00:00.0,2023-12-23T23:00:00.0,2023-12-23T00:00:00.0,2023-12-24T00:00:00.0
17,2023-12-24,53.0,26.0,2023-12-23T23:00:00.0,2023-12-24T23:00:00.0,2023-12-24T00:00:00.0,2023-12-25T00:00:00.0

# Random Forest

In [47]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
from sklearn.ensemble import RandomForestClassifier

In [50]:
# Zusammenführen der DataFrames basierend auf dem Datum
df_combined = pd.merge(df_stress, df_sleep, on='date', how='inner')
df_combined = pd.merge(df_combined, df_heart_rate, on='date', how='inner')
#df_combined = pd.merge(df_combined, df_body_battery, on='date', how='inner')

In [52]:
df_combined

,date,max_stress_level,average_stress_level,stress_duration,total_sleep_time,sleep_quality,max_heart_rate,min_heart_rate,resting_heart_rate
0,2023-12-07,97.0,43,24.000000,NaN,None,134.0,68.0,72.0
1,2023-12-08,92.0,38,24.000000,10.216667,None,124.0,65.0,69.0
2,2023-12-09,94.0,47,24.000000,8.316667,None,130.0,73.0,75.0
3,2023-12-10,82.0,34,24.000000,6.966667,None,110.0,70.0,73.0
4,2023-12-11,94.0,33,24.000000,5.950000,None,134.0,67.0,67.0
5,2023-12-12,98.0,39,24.000000,8.633333,None,128.0,68.0,69.0
6,2023-12-13,82.0,47,24.000000,7.866667,None,102.0,68.0,66.0
7,2023-12-14,94.0,33,24.000000,6.633333,None,123.0,65.0,69.0
8,2023-12-15,91.0,27,24.000000,8.916667,None,112.0,64.0,70.0
9,2023-12-16,93.0,22,24.000000,10.566667,None,127.0,63.0,65.0
10,2023-12-17,91.0,26,24.000000,7.016667,None,109.0,64.0,65.0
11,2023-12-18,93.0,20,24.000000,8.382222,None,126.0,60.0,62.0
12,2023-12-19,95.0,23,24.000000,6.400000,None,112.0,62.0,63.0
13,2023-12-20,99.0,32,24.000000,8.583333,None,127.0,40.0,55.0
14,2023-12-21,93.0,35,24.000000,6.983333,None,112.0,63.0,72.0
15,2023-12-22,98.0,33,24.000000,6.666667,None,142.0,64.0,67.0
16,2023-12-23,94.0,68,24.000000,8.383333,None,120.0,81.0,64.0
17,2023-12-24,97.0,29,24.000000,9.116667,None,119.0,66.0,68.0
18,2023-12-25,NaN,-1,24.000000,NaN,None,NaN,NaN,NaN
19,2023-12-26,NaN,-1,16.366667,NaN,None,NaN,NaN,NaN

In [51]:
# Drop NAN / NULL
df_combined = df_combined.drop(columns=["sleep_quality", "sleep_quality_score"]).dropna()

KeyError: "['sleep_quality_score'] not found in axis"

### Feature-Engineering
- Maximale tägliche Herzfrequenz: Höhere Werte könnten auf höheren Stress hindeuten.  
- Minimale tägliche Herzfrequenz: Niedrigere Werte in Ruhephasen könnten auf bessere Erholung hinweisen.  
- Durchschnittliche Stresslevel: Direkter Indikator für das Stresslevel.  
- Gesamtschlafzeit: Weniger Schlaf könnte mit höherem Stress verbunden sein.  
- Schlafqualität: Niedrigere Werte könnten auf schlechten Schlaf wegen Stress hindeuten.  

neue Features erstellen, indem wir vorhandene Daten transformieren, zb. durch Normalisierung oder das Erstellen von Verhältnissen zwischen verschiedenen Features.

In [31]:
# Feature-Engineering (Beispiel)
df_combined['normalized_max_heart_rate'] = df_combined['max_heart_rate'] / df_combined['max_heart_rate'].max()
df_combined['sleep_quality_score'] = df_combined['sleep_quality'] / 100  # Angenommen, Schlafqualität ist ein Wert zwischen 0 und 100

KeyError: 'sleep_quality'

### Zielvariable definieren
Stresslevel muss in kategorische Werte umgewandelt werden, falls sie nicht bereits in dieser Form vorliegen. Wir definieren "niedrig", "mittel" und "hoch" basierend auf den vorhandenen Stresslevel-Daten. Dies könnte beispielsweise durch Einteilung der average_stress_level in Quantile geschehen.

In [20]:
# Kategorisierung des durchschnittlichen Stresslevels in 'niedrig', 'mittel', 'hoch'
df_combined['stress_category'] = pd.qcut(df_combined['average_stress_level'], 3, labels=["niedrig", "mittel", "hoch"])

### Datensatz aufteilen
Nun teilen wir den Datensatz in Trainings- und Testdaten auf, um das Modell zu trainieren und zu evaluieren.

In [21]:
# Aufteilen des Datensatzes
X = df_combined.drop(['date', 'stress_category'], axis=1)  # Features
y = df_combined['stress_category']  # Zielvariable

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Modellauswahl und Training
- Random Forest ist gut geeignet für Klassifikationsaufgaben und kann mit nicht-linearen Beziehungen zwischen den Features umgehen.
- Er bietet eine eingebaute Methode zur Bewertung der Feature-Importanz, was für unser Verständnis von Stressfaktoren nützlich sein kann.
- Er ist robust gegenüber Overfitting, besonders wenn wir es mit einem relativ kleinen oder mittelgroßen Datensatz zu tun haben.
### Modell Initialisierung

In [22]:
# Initialisierung des Random Forest Classifiers
clf = RandomForestClassifier(n_estimators=100, random_state=42)

### Training des Modells
Mit unserem Trainingsdatensatz trainieren wir nun den Random Forest Classifier.

In [23]:
# Training des Modells
clf.fit(X_train, y_train)

ValueError: Input X contains NaN.
RandomForestClassifier does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

### Modellbewertung
Nach dem Training bewerten wir die Performance des Modells auf dem Testdatensatz. Wir können verschiedene Metriken wie Genauigkeit, F1-Score, Precision und Recall verwenden, um zu beurteilen, wie gut unser Modell bei der Klassifikation der Stresslevel performt.

In [ ]:
# Vorhersagen auf dem Testdatensatz
y_pred = clf.predict(X_test)

# Bewertung der Modellperformance
print("Genauigkeit:", accuracy_score(y_test, y_pred))
print("\nKlassifikationsbericht:\n", classification_report(y_test, y_pred))

### Feature-Importanz
Eine nützliche Eigenschaft des Random Forest Algorithmus ist, dass er uns ermöglicht, die Wichtigkeit der einzelnen Features für die Vorhersage zu ermitteln. Dies kann uns weitere Einblicke in die Faktoren geben, die Stress beeinflussen.

In [ ]:
feature_importances = pd.DataFrame(clf.feature_importances_,
                                   index = X_train.columns,
                                   columns=['importance']).sort_values('importance', ascending=False)

print(feature_importances)